### ISSUE TITLE
[Epic] 업체 도메인 생성/조회/수정/삭제 API 구현

### ISSUE THREAD

**Issue by zoohee** [NangManHub/nangman-hub#1]
## 📜 Description
- Company CRUD API 구현

## 🌈 Success criteria

- Company 생성 API 기본 기능 구현
- Company 조회 API 기본 기능 구현
- Company 수정 API 기본 기능 구현
- Company 삭제 API 기본 기능 구현
 
## 👷 To-do

- [x] JPA를 이용한 PostgreSQL 및 Redis와 Data access
- [x] 다른 서비스 개발 선작업이 필요한 일부 부분 더미 데이터 허용
- [x] API 별 접근 권한 설정
