### ISSUE TITLE
[Feature] 업체 생성 API 구현

### ISSUE THREAD

**Issue by zoohee** [NangManHub/nangman-hub#11]
## 📜 Description
- 업체 생성 API를 구현합니다.

## 🌈 Success criteria
- 업체 생성 API 구현 및 데이터 저장

## 👷 To-do
- [x] Controller method 구현
- [x] Service logic 구현
- [x] 접근 권한 제어 Interceptor 구현
- [x] 허브 담당자는 본인 허브에만 업체를 생성할 수 있음

##  🔗Related issues
Related to: #1
