### ISSUE TITLE
[Epic] Slack 도메인 메세징 처리

### ISSUE THREAD

**Issue by Kwonhyunjun** [NangManHub/nangman-hub#111]
## 📜 Description

Slack 도메인 API 구현 및 메세징 처리

## 🌈 Success criteria

Slack 도메인 API 구현 및 메세징 처리 완료

## 👷 To-do

- [X] 기본 세팅
- [X] 엔티티 생성
- [X] Slack 연동
- [X] Kafka 연동 및 Delivery 메세지 수신
- [X] Delivery 메세지 처리
- [X] AI 메세지 처리

##  🔗Related issues

Related to: #이슈번호
