### ISSUE TITLE
[Feature] Company 기본 파일 구성 및 엔티티 작성

### ISSUE THREAD

**Issue by zoohee** [NangManHub/nangman-hub#2]
## 📜 Description
- Company 도메인 관련 기본 파일 및 엔티티를 작성합니다.

## 🌈 Success criteria
- Company Controller, Entity, Service, Repository 생성

## 👷 To-do
- [x] Company Controller 생성
- [x] Company Entity 생성
- [x] Company Service 생성
- [x] Company Repository 생성
- [x] 기타 의존성 및 config 설정 

##  🔗Related issues
Related to: #1
