### ISSUE TITLE
[Feature] 업체 삭제 API 구현

### ISSUE THREAD

**Issue by zoohee** [NangManHub/nangman-hub#27]
## 📜 Description
- 업체 삭제 API를 구현합니다.

## 🌈 Success criteria
- 업체 삭제 API 구현
- soft delete 방법으로 삭제

## 👷 To-do
- [x]  실제 row 삭제는 진행하지 않고 deletedAt, deletedBy, isDelete 추가
- [x] Controller Delete Mapping
- [x] 업체 삭제 Service 로직 구현

##  🔗Related issues
Related to: #1
