### ISSUE TITLE
[Feature] User 엔티티 생성 및 기본 세팅

### ISSUE THREAD

**Issue by Kwonhyunjun** [NangManHub/nangman-hub#4]
## 📜 Description
User 도메인 엔티티 생성 및 기본 세팅

## 🌈 Success criteria
User 도메인 엔티티 생성 및 기본 세팅 완료

## 👷 To-do
- [X] 환경설정
- [X] 필요한 의존성 추가
- [X] 프로젝트 구조 설정 및 엔티티 생성
- [X] 글로벌 예외 처리 설정

##  🔗Related issues

Related to: #3
