### ISSUE TITLE
[Epic] 업체 도메인 생성/조회/수정/삭제/검색 API 코드 리팩토링

### ISSUE THREAD

**Issue by zoohee** [NangManHub/nangman-hub#46]
## 📜 Description
- 업체 도메인 코드 리뷰 및 리팩토링

## 🌈 Success criteria

- 주석 처리된 TODO를 전부 체크합니다.
- 객체지향적 코드 작성을 목표로 합니다.
- 내부 서비스와 통신하여 데이터를 주고 받습니다.

## 👷 To-do

- [x]  중복 코드 함수화
- [x] 서비스 로직 간소화
- [x] FeignClient 코드 테스트 및 수정

##  🔗Related issues

Related to: #1
