### ISSUE TITLE
[Feature] 상품 생성 API 구현

### ISSUE THREAD

**Issue by zoohee** [NangManHub/nangman-hub#50]
## 📜 Description
- 상품 생성 API를 구현합니다.

## 🌈 Success criteria
- 상품 생성 API 구현 및 데이터 저장

## 👷 To-do
- [x] Controller method 구현
- [x] Service logic 구현
- [x] 접근 권한 제어 어노테이션 적용
- [x] 허브 담당자(MANAGER)는 본인 허브에만 상품을 생성할 수 있음
- [x] 업체 관리자(AGENT)는 본인 업체만 상품을 생성할 수 있음

##  🔗Related issues
Related to: #48
