### ISSUE TITLE
[Epic] User/Shipper 서비스 버그 수정 및 리팩토링

### ISSUE THREAD

**Issue by Kwonhyunjun** [NangManHub/nangman-hub#96]
## 📜 Description

User/Shipper 서비스 버그 수정 및 리팩토링

## 🌈 Success criteria

User/Shipper 서비스 버그 수정 및 리팩토링 완료

## 👷 To-do

- [X] 유저 아이디와 비밀번호 정규식 설정
- [X] Shipper 생성 API PK 중복 예외처리
- [X] Shipper API 권한 및 요청 데이터 검증
- [X] Kafka Json 직렬화 추가 설정
- [X] CustomException HttpStatus 수정
- [X] JWT 만료 시간 설정 파일(properties)로 분리
